# Generated by Django 6.0.3 on 2026-04-20 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField(default=0, help_text='Cantidad física actual disponible en inventario.', verbose_name='Stock actual')),
                ('stock_reservado', models.PositiveIntegerField(default=0, help_text='Cantidad reservada temporalmente para procesos de compra.', verbose_name='Stock reservado')),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Umbral mínimo recomendado para reposición.', verbose_name='Stock mínimo')),
                ('activo_para_venta', models.BooleanField(default=True, help_text='Indica si este producto puede venderse actualmente.', verbose_name='Activo para venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='catalogo.juego', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario de producto',
                'verbose_name_plural': 'Inventarios de productos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('RESERVA', 'Reserva'), ('LIBERACION', 'Liberación'), ('VENTA_CONFIRMADA', 'Venta confirmada')], max_length=30, verbose_name='Tipo de movimiento')),
                ('origen', models.CharField(choices=[('ADMIN', 'Administración'), ('SISTEMA', 'Sistema'), ('PEDIDO', 'Pedido'), ('DEVOLUCION', 'Devolución'), ('AJUSTE', 'Ajuste manual')], default='SISTEMA', max_length=20, verbose_name='Origen')),
                ('cantidad', models.PositiveIntegerField(help_text='La cantidad siempre debe ser mayor a cero.', verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock anterior')),
                ('stock_posterior', models.PositiveIntegerField(verbose_name='Stock posterior')),
                ('motivo', models.CharField(help_text='Describe por qué se registró este movimiento.', max_length=255, verbose_name='Motivo')),
                ('referencia_externa', models.CharField(blank=True, help_text='Ejemplo: ID de pedido, devolución o proceso externo.', max_length=100, null=True, verbose_name='Referencia externa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventarioproducto', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='inventario_stock_actual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reservado__gte', 0)), name='inventario_stock_reservado_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='inventario_stock_minimo_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', models.F('stock_reservado'))), name='inventario_stock_actual_mayor_igual_reservado'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='movimiento_inventario_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_anterior__gte', 0)), name='movimiento_inventario_stock_anterior_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_posterior__gte', 0)), name='movimiento_inventario_stock_posterior_gte_0'),
        ),
    ]
