# Generated by Django 6.0.3 on 2026-04-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioproducto',
            options={'permissions': [('can_manage_inventory', 'Puede gestionar inventario')], 'verbose_name': 'Inventario de producto', 'verbose_name_plural': 'Inventarios de productos'},
        ),
    ]
