# Generated by Django 6.0.3 on 2026-04-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookPagoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='MERCADO_PAGO', max_length=30, verbose_name='Proveedor')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('query_params', models.JSONField(blank=True, null=True, verbose_name='Query params')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Headers')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de webhook de pago',
                'verbose_name_plural': 'Logs de webhook de pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], default='MERCADO_PAGO', max_length=30, verbose_name='Proveedor')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(default='ARS', max_length=10, verbose_name='Moneda')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID externo')),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de preferencia')),
                ('init_point', models.URLField(blank=True, null=True, verbose_name='URL de checkout')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta cruda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ordenes.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='pago_monto_gte_0')],
            },
        ),
    ]
