# Generated by Django 6.0.3 on 2026-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
