# Generated by Django 6.0.3 on 2026-04-21 17:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_juego_descripcion_alter_juego_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30, unique=True, verbose_name='Referencia')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_item', to='catalogo.juego', verbose_name='Juego')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.orden', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
            },
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='orden_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='orden_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='orden_item_cantidad_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='orden_item_precio_unitario_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='ordenitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='orden_item_subtotal_gte_0'),
        ),
    ]
